version: '3.5'


services:
  postgres:
    container_name: my_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
          - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
          - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
    driver: local